version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: budget_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: budget_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  # Flask App
  web:
    build: .
    container_name: budget_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_DATABASE=budget_db
    depends_on:
      - db

volumes:
  mysql_data: